openapi: 3.0.3
info:
  title: The Hotel API - OpenAPI 3.0
  description: |-
    Simple Api in order to test the opengenerator plugin features.
  contact:
    email: ellisonalves@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://localhost:8080/
tags:
  - name: booking
    description: Manage booking in the hotel
  - name: rooms
    description: Manage the hotel rooms
  - name: guests
    description: Manage the guests in the hotel
paths:
  /bookings:
    post:
      tags:
        - bookings
      summary: Creates a new booking
      description: Creates a booking in the hotel for a given customers and room for a determine period of timeØ
      operationId: createBooking
      requestBody:
        description: Creates a new booking
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookingRequest"
        required: true
      responses:
        "204":
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception

components:
  schemas:
    CreateBookingRequest:
      type: object
      properties:
        guest_id:
          type: string
          format: uuid
        room_id:
          type: string
          format: uuid
        from:
          type: string
          format: date-time
        until:
          type: string
          format: date-time
      required:
        - guest_id
        - room_id
        - from
        - until
